# Generated by Django 4.2.5 on 2023-09-26 08:00

import apps.export.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Success'), (4, 'Failure'), (5, 'Canceled')], default=1)),
                ('xlsx_file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=apps.export.models.questionnaire_export_file_upload_to)),
                ('xml_file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=apps.export.models.questionnaire_export_file_upload_to)),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
        ),
    ]
