# Generated by Django 4.2.5 on 2023-09-28 05:15

import apps.export.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Success'), (4, 'Failure'), (5, 'Canceled')], default=1)),
                ('xlsx_file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=apps.export.models.questionnaire_export_file_upload_to)),
                ('xml_file', models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=apps.export.models.questionnaire_export_file_upload_to)),
            ],
        ),
    ]
