# Generated by Django 4.2.1 on 2023-09-11 16:41

import apps.export.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireexport',
            old_name='file',
            new_name='xlsx_file',
        ),
        migrations.RemoveField(
            model_name='questionnaireexport',
            name='type',
        ),
        migrations.AddField(
            model_name='questionnaireexport',
            name='xml_file',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to=apps.export.models.questionnaire_export_file_upload_to),
        ),
    ]
