# Generated by Django 4.2.5 on 2023-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
