# Generated by Django 4.2.5 on 2023-10-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='errors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
