# Generated by Django 4.2.5 on 2023-09-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_remove_questionbank_is_draft_questionbank_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Started'), (3, 'Success'), (4, 'Failure')], default=1),
        ),
    ]
