# Generated by Django 4.2.5 on 2023-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionleafgroup',
            name='category_1',
            field=models.PositiveSmallIntegerField(choices=[(101, 'Context'), (102, 'Shocks and events'), (103, 'Displacement'), (104, 'Casualties'), (105, 'Information and communication'), (106, 'Humanitarian access'), (107, 'Introduction'), (108, 'Conclusion'), (109, 'Market'), (201, 'Impact'), (202, 'Humanitarian condition'), (203, 'At Risk'), (204, 'Priorities and preferences'), (205, 'Capacities and response')]),
        ),
        migrations.AlterField(
            model_name='questionleafgroup',
            name='category_2',
            field=models.PositiveSmallIntegerField(choices=[(10101, 'Introduction'), (10102, 'Politics'), (10103, 'Economics'), (10104, 'Environment'), (10105, 'Socio-cultural'), (10106, 'Demographics'), (10107, 'Security and stability'), (10201, 'Type and characteristics'), (10202, 'Aggravating factors'), (10203, 'Mitigating factors'), (10204, 'Threats and hazards'), (10301, 'Introduction people arriving'), (10302, 'Introduction people leaving'), (10304, 'Pull factors'), (10305, 'Push factors'), (10306, 'Intentions'), (10307, 'Local integration'), (10401, 'Dead'), (10402, 'Dead'), (10403, 'Injured'), (10404, 'Missing'), (10501, 'Communication sources and means'), (10502, 'Challenges and barriers'), (10503, 'Knowledge and information gaps (population)'), (10504, 'Knowledge and information gaps (humanitarians)'), (10601, 'Introduction humanitarian actors barriers'), (10602, 'Introduction people affected barriers'), (10603, 'Population to relief'), (10604, 'Relief to population'), (10605, 'Physical and security constraints'), (10606, 'People facing humanitarian access constraints/Humanitarian access gaps'), (10701, 'Questionnaire characteristics'), (10702, 'Enumerator characteristics'), (10703, 'Respondent characteristics'), (10704, 'Area characteristics'), (10705, 'Affected group characteristics'), (10901, 'Food'), (10902, 'Wash'), (10903, 'Shelter and domestic items'), (20101, 'Drivers'), (20102, 'Impact on people'), (20103, 'Impact on systems, services and networks'), (20104, 'Number of people affected'), (20201, 'Living standards'), (20202, 'Coping mechanisms'), (20203, 'Physical and mental well being'), (20204, 'Number of people in need'), (20301, 'People at risk'), (20302, 'Number of people at risk'), (20401, 'Priority needs'), (20402, 'Priority interventions'), (20501, 'Government and local authorities'), (20502, 'International organizations'), (20503, 'National and local organizations'), (20504, 'Red cross Red Crescent'), (20505, 'Humanitarian coordination'), (20506, 'People reached and response gaps')]),
        ),
        migrations.AlterField(
            model_name='questionleafgroup',
            name='category_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1001, 'Inter sector'), (1002, 'Health'), (1003, 'WASH'), (1004, 'Shelter'), (1005, 'Food security'), (1006, 'Livelihoods'), (1007, 'Nutrition'), (1008, 'Education'), (1009, 'Protection'), (1010, 'Agriculture'), (1011, 'Logistic')], null=True),
        ),
        migrations.AlterField(
            model_name='questionleafgroup',
            name='category_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10101, 'Introduction'), (10102, 'Cross'), (10201, 'Health care'), (10202, 'Health status'), (10301, 'Water supply'), (10302, 'Sanitation'), (10303, 'Solid waste management'), (10304, 'Hygiene'), (10305, 'WASH in schools'), (10306, 'WASH in health care facilities'), (10307, 'Vector control'), (10401, 'Dwelling envelope'), (10402, 'Domestic living space'), (10403, 'Non-food household items'), (10404, 'Housing, Land and Property (HLP)'), (10405, 'Settlement'), (10501, 'Food commodities'), (10502, 'Non Food Items'), (10601, 'Income'), (10602, 'Cash'), (10701, 'Nutrition status'), (10702, 'Nutrition services'), (10801, 'Provision'), (10802, 'Learning environment'), (10803, 'Teaching and learning'), (10804, 'Teachers and other education personnel'), (10805, 'Education policy'), (10901, 'Documentation'), (10902, 'Human, civil and political rights'), (10903, 'Justice and rule of law'), (10904, 'Physical safety and security'), (10905, 'Freedom of movement'), (10906, 'Child Protection'), (10907, 'Sexual and Gender-Based Violence'), (10908, 'Mines, UXOS and IEDs'), (11001, 'Production'), (11002, 'Agricultural inputs'), (11003, 'Agricultural infrastructure'), (11004, 'Natural resource management'), (11101, 'Transport'), (11102, 'Information and communication technologies (ICT)'), (11103, 'Energy')], null=True),
        ),
    ]
