# Generated by Django 4.2.1 on 2023-08-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='appearance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='calculation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_filter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='constraint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='default',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='guidance_hint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='is_or_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='or_other_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='parameters',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='readonly',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='relevant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='required_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='relevant',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
