# Generated by Django 4.2.5 on 2023-09-28 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_initial'),
        ('questionnaire', '0001_initial'),
        ('qbank', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='qbank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qbank.questionbank'),
        ),
        migrations.AddField(
            model_name='questionleafgroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionleafgroup',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionleafgroup',
            name='qbank_leaf_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='qbank.qbleafgroup'),
        ),
        migrations.AddField(
            model_name='questionleafgroup',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choicecollection'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='leaf_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionleafgroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='qbank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='qbank.qbquestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='choicecollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choicecollection',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choicecollection',
            name='qbank_choice_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='qbank.qbchoicecollection'),
        ),
        migrations.AddField(
            model_name='choicecollection',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire'),
        ),
        migrations.AddField(
            model_name='choice',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choicecollection'),
        ),
        migrations.AddField(
            model_name='choice',
            name='qbank_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='qbank.qbchoice'),
        ),
        migrations.AddIndex(
            model_name='questionleafgroup',
            index=models.Index(fields=['name'], name='questionnai_name_48d926_idx'),
        ),
        migrations.AddIndex(
            model_name='questionleafgroup',
            index=models.Index(fields=['order'], name='questionnai_order_1aedf4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionleafgroup',
            unique_together={('questionnaire', 'category_1', 'category_2', 'category_3', 'category_4'), ('questionnaire', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['name'], name='questionnai_name_992c67_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order'], name='questionnai_order_435c27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='choicecollection',
            unique_together={('questionnaire', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('collection', 'name')},
        ),
    ]
