# Generated by Django 4.2.5 on 2023-09-27 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_questionleafgroup_category_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='priority_level',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='data_collection_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Direct observation'), (2, 'Focus group'), (3, '1-on-1 interviews'), (4, 'Open-ended survey'), (5, 'Closed-ended survey'), (6, 'Key Informant Interview'), (7, 'Automatic')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='enumerator_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='priority_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]), blank=True, default=list, size=None),
        ),
    ]
