# Generated by Django 4.2.1 on 2023-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionleafgroup',
            name='label',
        ),
        migrations.AlterField(
            model_name='questionleafgroup',
            name='category_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3001, 'Water'), (3002, 'Sanitation'), (3003, 'Hygiene'), (3004, 'Waste Management'), (3005, 'Vector Control'), (4001, 'Health Care'), (4002, 'Health Status'), (5001, 'Documentation'), (5002, 'Civil And Political Rights'), (5003, 'Physical Safety And Security'), (5004, 'Freedom Of Movement'), (5005, 'Liberty'), (5006, 'Child Protection'), (5007, 'SGBV'), (5008, 'housing Land And Property'), (5009, 'Justice And Rule Of Law'), (5010, 'MINES'), (5011, 'Human Trafficking'), (6001, 'Learning Environment'), (6002, 'Facilities And Amenities'), (6003, 'Teacher And Learning'), (6004, 'Teachers And Education Personnel'), (7001, 'Income'), (7002, 'Expenditures'), (7003, 'Productive Assets'), (7004, 'Skills And Qualifications'), (8001, 'Nutrition Goods And Services'), (8002, 'Nutrition Status'), (12001, 'Dwelling Enveloppe'), (12002, 'Interior Domenstic Life')], null=True),
        ),
    ]
