# Generated by Django 4.2.1 on 2023-08-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_choicecollection_questionnaire_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'name')},
        ),
    ]
