# Generated by Django 4.2.1 on 2023-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_questionleafgroup_label_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='questionnai_order_435c27_idx',
            old_name='order_idx',
        ),
        migrations.AlterUniqueTogether(
            name='questionleafgroup',
            unique_together={('category_1', 'category_2', 'category_3', 'category_4'), ('questionnaire', 'name')},
        ),
        migrations.AddField(
            model_name='questionleafgroup',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['name'], name='questionnai_name_992c67_idx'),
        ),
        migrations.AddIndex(
            model_name='questionleafgroup',
            index=models.Index(fields=['name'], name='questionnai_name_48d926_idx'),
        ),
    ]
