# Generated by Django 4.2.1 on 2023-09-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_rename_order_idx_questionnai_order_435c27_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionleafgroup',
            unique_together={('questionnaire', 'category_1', 'category_2', 'category_3', 'category_4'), ('questionnaire', 'name')},
        ),
    ]
