# Generated by Django 4.2.1 on 2023-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Integer (i.e., whole number) input.'), (2, 'Decimal input.'), (3, 'Free text response.'), (4, 'Multiple choice question; only one answer can be selected.'), (5, 'Multiple choice question; multiple answers can be selected.'), (6, 'Rank question; order a list.'), (7, 'Range input (including rating)'), (10, 'Display a note on the screen, takes no input. Shorthand for type=text with readonly=true.'), (14, 'Date input.'), (15, 'Time input.'), (16, 'Accepts a date and a time input.'), (17, 'Take a picture or upload an image file.'), (18, 'Take an audio recording or upload an audio file.'), (20, 'Take a video recording or upload a video file.'), (21, 'Generic file input (txt, pdf, xls, xlsx, doc, docx, rtf, zip)'), (22, 'Scan a barcode, requires the barcode scanner app to be installed.'), (24, 'Acknowledge prompt that sets value to "OK" if selected.')]),
        ),
    ]
