# Generated by Django 4.2.1 on 2023-09-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_questionnaire_data_collection_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='question',
            name='or_other_label',
        ),
    ]
