# Generated by Django 4.2.1 on 2023-09-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_remove_choice_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data_collection_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Direct observation'), (2, 'Focus group'), (3, '1-on-1 interviews'), (4, 'Open-ended survey'), (5, 'Closed-ended survey'), (6, 'Key Informant Interview')], null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='enumerator_skill',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Basic'), (2, 'Medium'), (3, 'Advanced')], null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='priority_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='required_duration',
            field=models.PositiveIntegerField(blank=True, help_text='In seconds', null=True),
        ),
    ]
